import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { QueryProvider } from './provider';
import Link from 'next/link';
import UserLayout from '@/components/common/UserLayout';
import BorderLayout from '@/components/common/BorderLayout';

const inter = Inter({ subsets: ['latin'] });
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};
export default function RootLayout({
  children,
  modal
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <BorderLayout>
          <UserLayout />
          <QueryProvider>
            <Link href="/login"></Link>
            {children}
            {modal}
          </QueryProvider>
        </BorderLayout>
      </body>
    </html>
  );
}