import type { Metadata } from 'next';
import { Noto_Sans_KR } from 'next/font/google';
import localFont from 'next/font/local';
import Script from 'next/script';
import { ToastContainer } from 'react-toastify';
import { QueryProvider } from './provider';
import './globals.css';

export const metadata: Metadata = {
  title: '클룸',
  description: 'Generated by create next app'
};

const noto = Noto_Sans_KR({
  subsets: ['latin'] // 또는 preload: false
});

const pretendard = localFont({
  src: './fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920'
});

type Props = { children: React.ReactNode };

export default function RootLayout({ children }: Props) {
  const mapScriptSrc = `//dapi.kakao.com/v2/maps/sdk.js?appkey=${process.env.NEXT_PUBLIC_KAKAO_MAP_API_KEY}&libraries=services,clusterer&autoload=false`;
  return (
    <html lang="ko">
      <body className={pretendard.className}>
        <QueryProvider>
          <ToastContainer />
          {children}
          <Script src={mapScriptSrc} strategy="beforeInteractive" />
        </QueryProvider>
      </body>
    </html>
  );
}
