import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
// import './globals.css';
import UserLayout from '@/components/common/bars/UserLayout';
import BorderLayout from '@/components/common/bars/BorderLayout';

const inter = Inter({ subsets: ['latin'] });
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

interface ClrmRootLayoutProps {
  children: React.ReactNode;
}

export default function ClrmRootLayout({ children }: ClrmRootLayoutProps) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <BorderLayout>
          <UserLayout />
          {children}
        </BorderLayout>
      </body>
    </html>
  );
}
