import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
// import './globals.css';
import UserLayout from '@/components/common/bars/UserLayout';
import BorderLayout from '@/components/common/bars/BorderLayout';

const inter = Inter({ subsets: ['latin'] });
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

type Props = { children: React.ReactNode; modal: React.ReactNode };

export default function RootLayout({ children, modal }: Props) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <BorderLayout>
          <UserLayout />
          {children}
          {modal}
        </BorderLayout>
      </body>
    </html>
  );
}
